"""
research/abm/run_abm.py
=======================
CLI entry-point for running the retail FX sentiment ABM.

Loads a versioned research dataset from ``data/output/<version>/``, runs the
ABM simulation, prints a calibration comparison table, and optionally saves
the simulation output to disk.

Usage::

    python research/abm/run_abm.py --version 1.1.0
    python research/abm/run_abm.py --version 1.1.0 --steps 1000 --seed 42
    python research/abm/run_abm.py --version 1.1.0 \\
        --n-trend 60 --n-contrarian 60 --n-noise 20 \\
        --steps 2000 --output /tmp/abm_results.csv

Agent mix flags
---------------
--n-trend INT       Number of TrendFollower agents  (default: 40)
--n-contrarian INT  Number of Contrarian agents     (default: 40)
--n-noise INT       Number of NoiseTrader agents    (default: 20)

When no versioned dataset is available the script runs in synthetic mode
(price generated by GBM internally) and skips calibration comparison.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

# Ensure project root is on sys.path when run directly.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import numpy as np
import pandas as pd

import config as cfg
from utils.io import setup_logging
from research.abm.agents import Contrarian, NoiseTrader, TrendFollower
from research.abm.calibration import calibrate_from_dataset, compare_to_data
from research.abm.simulation import FXSentimentSimulation

logger = logging.getLogger(__name__)


def _parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Run the retail FX sentiment agent-based model.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--version",
        default=None,
        help="Dataset version to load for calibration (e.g. '1.1.0').  "
             "When omitted the simulation runs in synthetic mode.",
    )
    p.add_argument(
        "--variant",
        default="core",
        choices=["full", "core", "extended"],
        help="Dataset variant to load.",
    )
    p.add_argument("--pair", default=None, help="FX pair to use for calibration targets (e.g. 'eur-usd').")
    p.add_argument("--steps", type=int, default=500, help="Number of simulation steps to record.")
    p.add_argument("--seed", type=int, default=42, help="Random seed.")
    p.add_argument("--n-trend", type=int, default=40, help="Number of TrendFollower agents.")
    p.add_argument("--n-contrarian", type=int, default=40, help="Number of Contrarian agents.")
    p.add_argument("--n-noise", type=int, default=20, help="Number of NoiseTrader agents.")
    p.add_argument("--momentum-window", type=int, default=12, help="Momentum look-back window (bars).")
    p.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path to write simulation results CSV.  Skipped when omitted.",
    )
    p.add_argument(
        "--log-level",
        default=cfg.LOG_LEVEL,
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
    )
    return p.parse_args(argv)


def _build_agents(
    rng: np.random.Generator,
    n_trend: int,
    n_contrarian: int,
    n_noise: int,
    momentum_window: int,
):
    agents = []
    agents.extend(TrendFollower(rng, momentum_window=momentum_window) for _ in range(n_trend))
    agents.extend(Contrarian(rng, momentum_window=momentum_window) for _ in range(n_contrarian))
    agents.extend(NoiseTrader(rng) for _ in range(n_noise))
    return agents


def _load_real_data(version: str, variant: str) -> pd.DataFrame | None:
    suffix = "" if variant == "full" else f"_{variant}"
    filename = f"master_research_dataset{suffix}.csv"
    path = cfg.OUTPUT_DIR / version / filename
    if not path.exists():
        logger.warning("Dataset not found: %s  (running without calibration)", path)
        return None
    logger.info("Loading real dataset: %s", path)
    return pd.read_csv(path, parse_dates=["snapshot_time", "entry_time"])


def main(argv=None) -> None:
    args = _parse_args(argv)
    setup_logging(args.log_level)

    logger.info("=== FX Sentiment ABM ===")
    logger.info("  seed=%d  steps=%d  n_trend=%d  n_contrarian=%d  n_noise=%d",
                args.seed, args.steps, args.n_trend, args.n_contrarian, args.n_noise)

    rng = np.random.default_rng(args.seed)

    # Build agent population.
    total_agents = args.n_trend + args.n_contrarian + args.n_noise
    if total_agents == 0:
        logger.error("Total agent count is 0 — provide at least one agent type.")
        sys.exit(1)

    agents = _build_agents(rng, args.n_trend, args.n_contrarian, args.n_noise, args.momentum_window)
    logger.info("Population: %d trend + %d contrarian + %d noise = %d agents",
                args.n_trend, args.n_contrarian, args.n_noise, total_agents)

    # Run simulation.
    sim = FXSentimentSimulation(agents, rng=rng)
    sim_df = sim.run(n_steps=args.steps)

    # Print summary of simulated sentiment.
    logger.info("--- Simulation summary ---")
    logger.info("  net_sentiment: mean=%.2f  std=%.2f  abs_mean=%.2f",
                sim_df["net_sentiment"].mean(),
                sim_df["net_sentiment"].std(),
                sim_df["net_sentiment"].abs().mean())
    logger.info("  extreme_70 freq: %.3f",
                (sim_df["abs_sentiment"] >= 70).mean())

    # Calibration comparison (if dataset available).
    if args.version is not None:
        real_df = _load_real_data(args.version, args.variant)
        if real_df is not None:
            targets = calibrate_from_dataset(real_df, pair=args.pair)
            comparison = compare_to_data(sim_df, targets)
            logger.info("--- Calibration comparison ---\n%s", comparison.to_string(index=False))

    # Save output.
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        sim_df.to_csv(args.output, index=False)
        logger.info("Simulation results saved to %s", args.output)

    logger.info("Done.")


if __name__ == "__main__":
    main()
